file:
  storage_dir: "filestorage/images/"
  client: "/images/**"
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mobilebanking2
    username: postgres
    password: lyhou123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8888
springdoc:
  swagger-ui:
    path: /api-docs
